apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials

# if we wanna use data: string value should be encoded with base64
#echo "abcdefghiklmno" | base64

data:
  accessKey: MTIzNDU2Nzg5MAo= #original value: 1234567890
  secretKey: YWJjZGVmZ2hpa2xtbm8K # original value: abcdefghiklmno

#with stringData, k8s will automatically encode it with base64

stringData:
  accessKey: "1234567890"
  secretKey: "abcdefghiklmno"