---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: NodePort
  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
      
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker 
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - name: api-port
      port: 8080
      targetPort: 8080
      nodePort: 30025
  
      
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
      nodePort: 30040
  
      
