apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
      nodePort: 30040
  
      
