apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker 
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020
      protocol: TCP